name: first-workflow_test_0

on: [push]

jobs:
  git-workflow-job_0: 
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v



          